routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::group(['namespace' => 'Admin','prefix'=>'admin','as'=>'admin.'], function () {

    Route::group(['namespace' => 'Auth'], function () {
        Route::get('login', 'LoginController@login')->name('login');
        Route::post('login', 'LoginController@loginSubmit')->name('submit');
        Route::post('logout', 'LoginController@logout')->name('logout');
    });

    Route::group(['middleware'=>['auth:admin']], function () {
        Route::get('dashboard', 'AdminController@index')->name('dashboard');
        Route::get('track-order', 'AdminController@trackOrder')->name('track-order');


        Route::group(['prefix'=>'rider','as'=>'rider.'], function () {
            Route::get('view', 'RiderController@index')->name('view');
            Route::get('register', 'RiderController@register')->name('register');
            Route::post('register', 'RiderController@store')->name('store');
            Route::get('edit/{id}', 'RiderController@edit')->name('edit');
            Route::post('edit', 'RiderController@update')->name('update');
        });
        Route::group(['prefix'=>'merchant','as'=>'merchant.'], function () {
            Route::get('approve', 'MerchantController@approve')->name('approve');
            Route::get('request', 'MerchantController@request')->name('request');
            Route::get('reject', 'MerchantController@reject')->name('reject');
            Route::post('register', 'MerchantController@store')->name('store');
            Route::get('plan', 'MerchantController@plan')->name('plan');
            Route::post('plan', 'MerchantController@updatePlan')->name('update-plan');
            Route::post('edit', 'MerchantController@update')->name('update');
            Route::post('status', 'MerchantController@status')->name('status');
        });
        Route::group(['prefix'=>'business','as'=>'business.'], function () {
            Route::get('plan', 'BusinessSettingController@plan')->name('plan');
            Route::post('store-plan', 'BusinessSettingController@storePlan')->name('store-plan');
            Route::post('update-plan', 'BusinessSettingController@updatePlan')->name('update-plan');
            Route::get('coverage-area', 'BusinessSettingController@coverageArea')->name('coverage-area');
            Route::post('store-coverage-area', 'BusinessSettingController@StoreCoverageArea')->name('store-coverage-area');
            Route::post('status', 'BusinessSettingController@status')->name('status');
        });
        Route::group(['prefix'=>'order','as'=>'order.'], function () {
            Route::get('pending', 'OrderController@pending')->name('pending');
            Route::get('confirm', 'OrderController@confirm')->name('confirm');
            Route::get('shipped', 'OrderController@shipped')->name('shipped');
            Route::get('delivered', 'OrderController@delivered')->name('delivered');
            Route::get('print/{id}', 'OrderController@print')->name('print');
            Route::get('view', 'OrderController@view')->name('view');
            Route::get('edit/{id}', 'OrderController@edit')->name('edit');
            Route::post('edit', 'OrderController@update')->name('update');
            Route::post('search-shop', 'OrderController@searchShop')->name('search-shop');
            Route::post('search-shop', 'OrderController@searchShop')->name('search-shop');
            Route::post('delivery-charge-plan', 'OrderController@deliveryChargePlan')->name('delivery-charge-plan');
            Route::post('fetch-delivery', 'OrderController@fetchDelivery')->name('fetch-delivery');
            Route::get('delivery', 'OrderController@delivery')->name('delivery');
            Route::get('pending', 'OrderController@pending')->name('pending');
            Route::post('fetch-data', 'OrderController@fetchData')->name('fetch-data');
            Route::post('fetch-data-assign', 'OrderController@fetchDataAssign')->name('fetch-data-assign');
            Route::post('search-data', 'OrderController@searchData')->name('search-data');
            Route::post('status', 'OrderController@status')->name('status');
            Route::post('single-status', 'OrderController@singleStatus')->name('single-status');
        });
        Route::group(['prefix'=>'pickup','as'=>'pickup.'], function () {
            Route::get('list', 'PickupController@list')->name('list');
            Route::get('approve', 'PickupController@approve')->name('approve');
            Route::post('status', 'PickupController@status')->name('status');
        });
        Route::group(['prefix'=>'payment','as'=>'payment.'], function () {
            Route::get('rider-payment', 'PaymentController@riderPayment')->name('rider-payment');
            Route::get('rider-payment-list', 'PaymentController@riderPaymentList')->name('rider-payment-list');
            Route::post('rider-payment', 'PaymentController@riderPaymentStore')->name('rider-payment-store');
            Route::get('merchant-payment-invoice', 'PaymentController@createMerchantPaymentInvoice')->name('merchant-payment-invoice');
            Route::post('merchant-payment-invoice', 'PaymentController@createMerchantPaymentInvoiceStore')->name('merchant-payment-invoice-store');
            Route::get('merchant-invoice-list', 'PaymentController@merchantPaymentInvoiceList')->name('merchant-invoice-list');
        });
    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use App\Mail\MerchantRegistration;
use Illuminate\Support\Facades\Mail;

Route::get('/', function () {
    return view('welcome');
});
Route::get('/clear-cache', function() {
    $exitCode = Artisan::call('cache:clear');
    $exitCode = Artisan::call('config:cache');
    return 'DONE'; //Return anything
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Rider.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Rider extends Model
{
    //
}

app/Http/Controllers/Admin/RiderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Merchant;
use App\Rider;
use Carbon\Carbon;
use Illuminate\Http\Request;

class RiderController extends Controller
{
    public function index()
    {
        return view('admins.riders.view');
    }

    public function register()
    {
        return view('admins.riders.register');
    }

    public function store(Request $request)
    {
        if (empty(Rider::where('email',$request->email)->first()) ) {
            $pv= Carbon::now()->toDateString() . "-" . uniqid();
            $rider_verification_id_pic = $request->verification_id_pic;
            $imageName = $rider_verification_id_pic->getClientOriginalName();
            $extension = pathinfo($imageName, PATHINFO_EXTENSION);
            $imagemove = $rider_verification_id_pic->move('public/storage/rider/verification_image', $pv . "." . $extension);
            $name = array("photo" => $pv. "." . $extension,);
            $verificationIdPic = asset('public/storage/rider/verification_image/'. $pv . "." . $extension);

            $pp=Carbon::now()->toDateString() . "-" . uniqid();
            $rider_profile_pic = $request->profile_pic;
            $imageName = $rider_profile_pic->getClientOriginalName();
            $extension = pathinfo($imageName, PATHINFO_EXTENSION);
            $imagemove = $rider_profile_pic->move('public/storage/rider/profile_image',  $pp. "." . $extension);
            $name = array("photo" => $pp . "." . $extension,);
            $profilePic = asset('public/storage/rider/profile_image/'. $pp . "." . $extension);


            $rider = new Rider;
            $rider->name =$request->name;
            $rider->nick_name =$request->nick_name;
            $rider->email =$request->email;
            $rider->phone =$request->phone;
            $rider->father_name =$request->father_name;
            $rider->mother_name =$request->mother_name;
            $rider->present_address =$request->present_address;
            $rider->permanent_address =$request->permanent_address;
            $rider->verification_id_type =$request->verification_id_type;
            $rider->verification_id_number =$request->verification_id_number;
            $rider->verification_id_pic =$verificationIdPic;
            $rider->profile_pic =$profilePic;
            $rider->referrer_name =$request->referrer_name;
            $rider->referrer_phone =$request->referrer_phone;
            $rider->referrer_address =$request->referrer_address;
            $rider->save();
            toastr()->success('Rider registered successfully');
            return redirect()->back();
        }
        toastr()->error('Rider already registered.');
        return redirect()->back();
    }

    public function edit($id)
    {
        $rider = Rider::findOrFail(decrypt($id));
        return view('admins.riders.edit',compact('rider'));
    }

    public function update(Request $request)
    {
        $rider = Rider::where('id',$request->id)->first();
        $rider->name =$request->name;
        $rider->nick_name =$request->nick_name;
        $rider->email =$request->email;
        $rider->phone =$request->phone;
        $rider->father_name =$request->father_name;
        $rider->mother_name =$request->mother_name;
        $rider->present_address =$request->present_address;
        $rider->permanent_address =$request->permanent_address;
        $rider->verification_id_type =$request->verification_id_type;
        $rider->verification_id_number =$request->verification_id_number;
        $rider->referrer_name =$request->referrer_name;
        $rider->referrer_phone =$request->referrer_phone;
        $rider->referrer_address =$request->referrer_address;
        $rider->save();

        toastr()->success("Rider updated successfully.");
        return redirect()->route('admin.rider.view');
    }


}

resources/views/admins/riders/view.blade.php
@extends('admins.layouts.app')
@section('title')
    View Riders
@stop
@section('rider','active')
@section('collapsed-rider','')
@section('rider-c','show')
@section('RL','active')
@section('css')

@stop

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <div class="row p-0">
                        <div class="col text-left">
                            <h3>View Riders</h3>
                        </div>
                        <div class="col text-right">
                            <a href="{{route('admin.rider.register')}}" class="btn btn-admin-primary">Add Rider</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped" id="dataTable" width="100%" >
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Nick Name</th>
                                <th>Email</th>
                                <th>Phone Number</th>
                                <th>Present Address</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach(\App\Rider::orderBy('id','desc')->get() as $key=> $rider)
                                <tr>
                                    <td>{{$key+1}}</td>
                                    <td>{{$rider->nick_name}}</td>
                                    <td>{{$rider->email}}</td>
                                    <td>{{$rider->phone}}</td>
                                    <td>{{$rider->present_address}}</td>
                                    <td>{{$rider->status}}</td>
                                    <td>
                                        <a href="" class="btn btn-admin-primary" data-toggle="modal" data-target="#riderModal{{$rider->id}}"><i class='fas fa-eye'></i></a>
                                        <a href="{{route('admin.rider.edit', encrypt($rider->id))}}" class="btn btn-admin-secondary"><i class='fas fa-wrench'></i></a>
                                    </td>
                                </tr>
                                <!-- Modal -->
                                <div class="modal fade" id="riderModal{{$rider->id}}" role="dialog">
                                    <div class="modal-dialog modal-xl">
                                        <!-- Modal content-->
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h4 class="modal-title">Rider Info</h4>
                                                <button type="button" class="close btn btn-admin-danger" data-dismiss="modal">&times;</button>
                                            </div>
                                            <div class="modal-body">
                                                <div class="container">
                                                    <div class="row">
                                                        <div class="col-md-6">
                                                            <!-- Account details card-->
                                                            <div class="card mb-4">
                                                                <div class="card-header">Personal Information</div>
                                                                <div class="card-body">
                                                                    <div class="row">
                                                                        <div class="form-group col-md-6">
                                                                            <span class="heading"><u>Full Name :</u></span>
                                                                            <h6><b>{{$rider->name}}</b></h6>
                                                                        </div>
                                                                        <div class="form-group col-md-6">
                                                                            <span class="heading"><u>Nick Name :</u></span>
                                                                            <h6><b>{{$rider->nick_name}}</b></h6>
                                                                        </div>
                                                                    </div>
                                                                    <div class="row">
                                                                        <div class="form-group col-md-6">
                                                                            <span class="heading"><u>Email :</u></span>
                                                                            <h6><b>{{$rider->email}}</b></h6>
                                                                        </div>
                                                                        <div class="form-group col-md-6">
                                                                            <span class="heading"><u>Mobile Number :</u></span>
                                                                            <h6><b>{{$rider->phone}}</b></h6>
                                                                        </div>
                                                                    </div>
                                                                    <div class="row">
                                                                        <div class="form-group col-md-6">
                                                                            <span class="heading"><u>Father Name :</u></span>
                                                                            <h6><b>{{$rider->father_name}}</b></h6>
                                                                        </div>
                                                                        <div class="form-group col-md-6">
                                                                            <span class="heading"><u>Mother Name :</u></span>
                                                                            <h6><b>{{$rider->mother_name}}</b></h6>
                                                                        </div>
                                                                    </div>
                                                                    <div class="row">
                                                                        <div class="form-group col-md-6">
                                                                            <span class="heading"><u>Present Address :</u></span>
                                                                            <h6><b>{{$rider->present_address}}</b></h6>
                                                                        </div>
                                                                        <div class="form-group col-md-6">
                                                                            <span class="heading"><u>Permanent Address :</u></span>
                                                                            <h6><b>{{$rider->permanent_address}}</b></h6>
                                                                        </div>
                                                                    </div>
                                                                    <div class="row">
                                                                        <div class="form-group col-md-6">
                                                                            <span class="heading"><u>Referrer Name :</u></span>
                                                                            <h6><b>{{$rider->referrer_name}}</b></h6>
                                                                        </div>
                                                                        <div class="form-group col-md-6">
                                                                            <span class="heading"><u>Referrer Mobile Number:</u></span>
                                                                            <h6><b>{{$rider->referrer_phone}}</b></h6>
                                                                        </div>
                                                                    </div>
                                                                    <div class="row">
                                                                        <div class="form-group col-md-6">
                                                                            <span class="heading"><u>Referrer Address :</u></span>
                                                                            <h6><b>{{$rider->referrer_address}}</b></h6>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="col-md-6">
                                                            <!-- Profile picture card-->
                                                            <div class="card">
                                                                <div class="card-header">Verification details </div>
                                                                <div class="card-body">
                                                                    <div class="row">
                                                                        <div class="form-group col-md-6">
                                                                            <span class="heading"><u>Verification Type</u></span>
                                                                            <h6><b>{{$rider->verification_id_type}}</b></h6>
                                                                        </div>
                                                                        <div class="form-group col-md-6">
                                                                            <span class="heading"><u>{{$rider->verification_id_type}} Number</u></span>
                                                                            <h6><b>{{$rider->verification_id_number}}</b></h6>
                                                                        </div>
                                                                    </div>
                                                                    <div class="row">
                                                                        <div class="col-md-6">
                                                                            <span><u>Profile Pic :</u></span><br>
                                                                            <img class="img-account-profile rounded-circle mb-2" src="{{$rider->profile_pic}}" alt="" width="100" height="100">
                                                                        </div>
                                                                        <div class="col-md-6">
                                                                            <span><u>{{$rider->verification_id_type}} Pic :</u></span><br>
                                                                            <img class="img-account-profile mb-2" src="{{$rider->verification_id_pic}}" alt="" width="280" height="220">
                                                                        </div>
                                                                     </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>

                                                </div>
                                            </div>
                                            <div class="modal-footer">
                                                <a href="{{route('admin.rider.edit', encrypt($rider->id))}}" class="btn btn-admin-secondary"><i class='fas fa-wrench'></i> Edit</a>
                                                <button type="button" class="btn btn-admin-danger" data-dismiss="modal">Close</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- End Modal -->

                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>


@stop
@section('script')
    @toastr_render
    <script>
        $("#dataTable").dataTable();
    </script>
@stop