routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::group(['namespace' => 'Admin','prefix'=>'admin','as'=>'admin.'], function () {

    Route::group(['namespace' => 'Auth'], function () {
        Route::get('login', 'LoginController@login')->name('login');
        Route::post('login', 'LoginController@loginSubmit')->name('submit');
        Route::post('logout', 'LoginController@logout')->name('logout');
    });

    Route::group(['middleware'=>['auth:admin']], function () {
        Route::get('dashboard', 'AdminController@index')->name('dashboard');
        Route::get('track-order', 'AdminController@trackOrder')->name('track-order');


        Route::group(['prefix'=>'rider','as'=>'rider.'], function () {
            Route::get('view', 'RiderController@index')->name('view');
            Route::get('register', 'RiderController@register')->name('register');
            Route::post('register', 'RiderController@store')->name('store');
            Route::get('edit/{id}', 'RiderController@edit')->name('edit');
            Route::post('edit', 'RiderController@update')->name('update');
        });
        Route::group(['prefix'=>'merchant','as'=>'merchant.'], function () {
            Route::get('approve', 'MerchantController@approve')->name('approve');
            Route::get('request', 'MerchantController@request')->name('request');
            Route::get('reject', 'MerchantController@reject')->name('reject');
            Route::post('register', 'MerchantController@store')->name('store');
            Route::get('plan', 'MerchantController@plan')->name('plan');
            Route::post('plan', 'MerchantController@updatePlan')->name('update-plan');
            Route::post('edit', 'MerchantController@update')->name('update');
            Route::post('status', 'MerchantController@status')->name('status');
        });
        Route::group(['prefix'=>'business','as'=>'business.'], function () {
            Route::get('plan', 'BusinessSettingController@plan')->name('plan');
            Route::post('store-plan', 'BusinessSettingController@storePlan')->name('store-plan');
            Route::post('update-plan', 'BusinessSettingController@updatePlan')->name('update-plan');
            Route::get('coverage-area', 'BusinessSettingController@coverageArea')->name('coverage-area');
            Route::post('store-coverage-area', 'BusinessSettingController@StoreCoverageArea')->name('store-coverage-area');
            Route::post('status', 'BusinessSettingController@status')->name('status');
        });
        Route::group(['prefix'=>'order','as'=>'order.'], function () {
            Route::get('pending', 'OrderController@pending')->name('pending');
            Route::get('confirm', 'OrderController@confirm')->name('confirm');
            Route::get('shipped', 'OrderController@shipped')->name('shipped');
            Route::get('delivered', 'OrderController@delivered')->name('delivered');
            Route::get('print/{id}', 'OrderController@print')->name('print');
            Route::get('view', 'OrderController@view')->name('view');
            Route::get('edit/{id}', 'OrderController@edit')->name('edit');
            Route::post('edit', 'OrderController@update')->name('update');
            Route::post('search-shop', 'OrderController@searchShop')->name('search-shop');
            Route::post('search-shop', 'OrderController@searchShop')->name('search-shop');
            Route::post('delivery-charge-plan', 'OrderController@deliveryChargePlan')->name('delivery-charge-plan');
            Route::post('fetch-delivery', 'OrderController@fetchDelivery')->name('fetch-delivery');
            Route::get('delivery', 'OrderController@delivery')->name('delivery');
            Route::get('pending', 'OrderController@pending')->name('pending');
            Route::post('fetch-data', 'OrderController@fetchData')->name('fetch-data');
            Route::post('fetch-data-assign', 'OrderController@fetchDataAssign')->name('fetch-data-assign');
            Route::post('search-data', 'OrderController@searchData')->name('search-data');
            Route::post('status', 'OrderController@status')->name('status');
            Route::post('single-status', 'OrderController@singleStatus')->name('single-status');
        });
        Route::group(['prefix'=>'pickup','as'=>'pickup.'], function () {
            Route::get('list', 'PickupController@list')->name('list');
            Route::get('approve', 'PickupController@approve')->name('approve');
            Route::post('status', 'PickupController@status')->name('status');
        });
        Route::group(['prefix'=>'payment','as'=>'payment.'], function () {
            Route::get('rider-payment', 'PaymentController@riderPayment')->name('rider-payment');
            Route::get('rider-payment-list', 'PaymentController@riderPaymentList')->name('rider-payment-list');
            Route::post('rider-payment', 'PaymentController@riderPaymentStore')->name('rider-payment-store');
            Route::get('merchant-payment-invoice', 'PaymentController@createMerchantPaymentInvoice')->name('merchant-payment-invoice');
            Route::post('merchant-payment-invoice', 'PaymentController@createMerchantPaymentInvoiceStore')->name('merchant-payment-invoice-store');
            Route::get('merchant-invoice-list', 'PaymentController@merchantPaymentInvoiceList')->name('merchant-invoice-list');
        });
    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use App\Mail\MerchantRegistration;
use Illuminate\Support\Facades\Mail;

Route::get('/', function () {
    return view('welcome');
});
Route::get('/clear-cache', function() {
    $exitCode = Artisan::call('cache:clear');
    $exitCode = Artisan::call('config:cache');
    return 'DONE'; //Return anything
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/PickupController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Order;
use App\Status;
use App\TrackOrder;
use Illuminate\Http\Request;

class PickupController extends Controller
{
    public function approve()
    {
        return view('admins.pickups.approve');
    }
    public function list()
    {
        return view('admins.pickups.list');
    }
    public function status(Request $request)
    {
        $id1 = $request->id;
        if ($id1=="")
        {
            toastr()->error("Order not added.");
            return redirect()->back();
        }
        $id = array_unique($id1);
        for ($i=0;$i<count($id);$i++)
        {
            for ($i=0;$i<count($id);$i++)
            {
                $order = Order::where('id',$id[$i])->first();
                $order->delivery_status = $request->delivery_status;
                $order->save();
                $tracking = new TrackOrder;
                $tracking->tracking_id = $order->tracking_id;
                $tracking->status_id=$request->delivery_status;
                $tracking->save();
            }
            toastr()->success("Order status change successfully.");
            return redirect()->back();
        }
    }
}

resources/views/admins/pickups/approve.blade.php
@extends('admins.layouts.app')
@section('title')
    Pickup Approve
@stop
@section('pickup','active')
@section('collapsed-pickup','')
@section('pickup-c','show')
@section('PA','active')
@section('css')

@stop

@section('content')

    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <h1>Pickup Approve</h1>
                </div>
                <div class="card-body">
                    <form action="{{route('admin.pickup.status')}}" method="post">
                        @csrf
                        <div class="table-responsive">
                            <table class="table table-striped" id="dataTable" width="100%" >
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Track ID</th>
                                    <th>Shop Name</th>
                                    <th>Customer Name</th>
                                    <th>Customer Phone</th>
                                </tr>
                                </thead>
                                <tbody>
                                    @foreach(\App\Order::where('delivery_status',1)->get() as $key=> $order)
                                        <tr>
                                            <td><input type="hidden" name="id[]" value="{{$order->id}}"> {{$key+1}}</td>
                                            <td>{{$order->tracking_id}}</td>
                                            <td>{{$order->merchantShop->shop_name}}</td>
                                            <td>{{$order->recipient_name}}</td>
                                            <td>{{$order->recipient_phone}}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        <div class="row mt-2">
                            <input type="hidden" name="delivery_status" value="2">
                            <div class="offset-md-8 col-md-4">
                                <button type="submit" class="btn btn-admin-primary float-right mk">Pickup Approved</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@stop
@section('script')
    @toastr_render
    <script>
        $("#dataTable").dataTable();
    </script>
@stop

resources/views/admins/pickups/confirm.blade.php
<?php

resources/views/admins/pickups/list.blade.php
@extends('admins.layouts.app')
@section('title')
    Pickup List
@stop
@section('pickup','active')
@section('collapsed-pickup','')
@section('pickup-c','show')
@section('PL','active')
@section('css')

@stop

@section('content')

    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <h3>Pickup List</h3>
                </div>
                <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped" id="dataTable" width="100%" >
                                <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Shop Name</th>
                                    <th>Shop Number</th>
                                    <th>Shop Area</th>
                                    <th>Shop Address</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach(\App\Order::select('shop_id')->where('delivery_status',2)->whereDate('updated_at',\Carbon\Carbon::today())->groupBy('shop_id')->get() as $key=> $shop_id)
{{--                                    {{$shop_id}}--}}
                                    <?php $shop=\App\MerchantShop::where('id',$shop_id->shop_id)->first() ?>
                                        <tr>
                                            <td> {{$key+1}}</td>
                                            <td>{{$shop->shop_name}}</td>
                                            <td>{{$shop->pickup_number}}</td>
                                            <td>{{$shop->pickUpArea->area}}</td>
                                            <td>{{$shop->pickup_address}}</td>
                                        </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                </div>
            </div>
        </div>
    </div>
@stop
@section('script')
    @toastr_render
    <script>
        $("#dataTable").dataTable();
    </script>
@stop