routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::group(['namespace' => 'Admin','prefix'=>'admin','as'=>'admin.'], function () {

    Route::group(['namespace' => 'Auth'], function () {
        Route::get('login', 'LoginController@login')->name('login');
        Route::post('login', 'LoginController@loginSubmit')->name('submit');
        Route::post('logout', 'LoginController@logout')->name('logout');
    });

    Route::group(['middleware'=>['auth:admin']], function () {
        Route::get('dashboard', 'AdminController@index')->name('dashboard');
        Route::get('track-order', 'AdminController@trackOrder')->name('track-order');


        Route::group(['prefix'=>'rider','as'=>'rider.'], function () {
            Route::get('view', 'RiderController@index')->name('view');
            Route::get('register', 'RiderController@register')->name('register');
            Route::post('register', 'RiderController@store')->name('store');
            Route::get('edit/{id}', 'RiderController@edit')->name('edit');
            Route::post('edit', 'RiderController@update')->name('update');
        });
        Route::group(['prefix'=>'merchant','as'=>'merchant.'], function () {
            Route::get('approve', 'MerchantController@approve')->name('approve');
            Route::get('request', 'MerchantController@request')->name('request');
            Route::get('reject', 'MerchantController@reject')->name('reject');
            Route::post('register', 'MerchantController@store')->name('store');
            Route::get('plan', 'MerchantController@plan')->name('plan');
            Route::post('plan', 'MerchantController@updatePlan')->name('update-plan');
            Route::post('edit', 'MerchantController@update')->name('update');
            Route::post('status', 'MerchantController@status')->name('status');
        });
        Route::group(['prefix'=>'business','as'=>'business.'], function () {
            Route::get('plan', 'BusinessSettingController@plan')->name('plan');
            Route::post('store-plan', 'BusinessSettingController@storePlan')->name('store-plan');
            Route::post('update-plan', 'BusinessSettingController@updatePlan')->name('update-plan');
            Route::get('coverage-area', 'BusinessSettingController@coverageArea')->name('coverage-area');
            Route::post('store-coverage-area', 'BusinessSettingController@StoreCoverageArea')->name('store-coverage-area');
            Route::post('status', 'BusinessSettingController@status')->name('status');
        });
        Route::group(['prefix'=>'order','as'=>'order.'], function () {
            Route::get('pending', 'OrderController@pending')->name('pending');
            Route::get('confirm', 'OrderController@confirm')->name('confirm');
            Route::get('shipped', 'OrderController@shipped')->name('shipped');
            Route::get('delivered', 'OrderController@delivered')->name('delivered');
            Route::get('print/{id}', 'OrderController@print')->name('print');
            Route::get('view', 'OrderController@view')->name('view');
            Route::get('edit/{id}', 'OrderController@edit')->name('edit');
            Route::post('edit', 'OrderController@update')->name('update');
            Route::post('search-shop', 'OrderController@searchShop')->name('search-shop');
            Route::post('search-shop', 'OrderController@searchShop')->name('search-shop');
            Route::post('delivery-charge-plan', 'OrderController@deliveryChargePlan')->name('delivery-charge-plan');
            Route::post('fetch-delivery', 'OrderController@fetchDelivery')->name('fetch-delivery');
            Route::get('delivery', 'OrderController@delivery')->name('delivery');
            Route::get('pending', 'OrderController@pending')->name('pending');
            Route::post('fetch-data', 'OrderController@fetchData')->name('fetch-data');
            Route::post('fetch-data-assign', 'OrderController@fetchDataAssign')->name('fetch-data-assign');
            Route::post('search-data', 'OrderController@searchData')->name('search-data');
            Route::post('status', 'OrderController@status')->name('status');
            Route::post('single-status', 'OrderController@singleStatus')->name('single-status');
        });
        Route::group(['prefix'=>'pickup','as'=>'pickup.'], function () {
            Route::get('list', 'PickupController@list')->name('list');
            Route::get('approve', 'PickupController@approve')->name('approve');
            Route::post('status', 'PickupController@status')->name('status');
        });
        Route::group(['prefix'=>'payment','as'=>'payment.'], function () {
            Route::get('rider-payment', 'PaymentController@riderPayment')->name('rider-payment');
            Route::get('rider-payment-list', 'PaymentController@riderPaymentList')->name('rider-payment-list');
            Route::post('rider-payment', 'PaymentController@riderPaymentStore')->name('rider-payment-store');
            Route::get('merchant-payment-invoice', 'PaymentController@createMerchantPaymentInvoice')->name('merchant-payment-invoice');
            Route::post('merchant-payment-invoice', 'PaymentController@createMerchantPaymentInvoiceStore')->name('merchant-payment-invoice-store');
            Route::get('merchant-invoice-list', 'PaymentController@merchantPaymentInvoiceList')->name('merchant-invoice-list');
        });
    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


use App\Mail\MerchantRegistration;
use Illuminate\Support\Facades\Mail;

Route::get('/', function () {
    return view('welcome');
});
Route::get('/clear-cache', function() {
    $exitCode = Artisan::call('cache:clear');
    $exitCode = Artisan::call('config:cache');
    return 'DONE'; //Return anything
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/BusinessSettingController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Area;
use App\City;
use App\CoverageArea;
use App\Http\Controllers\Controller;
use App\Plan;
use Illuminate\Http\Request;

class BusinessSettingController extends Controller
{
    public function plan()
    {
        return view('admins.business-settings.plan');
    }
    public function storePlan(Request $request)
    {

        if (empty(Plan::where('plan_name',$request->plan_name)->first()) ) {
            $plan = new Plan;
            $plan->plan_name =$request->plan_name;
            $plan->idr_charge =$request->idr_charge;
            if ($request->idr_cod=="on")
            {
                $plan->idr_cod =1;
            }
            else
            {
                $plan->idr_cod =0;
            }
            $plan->idu_charge =$request->idu_charge;
            if ($request->idr_cod=="on")
            {
                $plan->idu_cod =1;
            }
            else
            {
                $plan->idu_cod =0;
            }
            $plan->ds_charge =$request->ds_charge;
            if ($request->ds_cod=="on")
            {
                $plan->ds_cod =1;
            }
            else
            {
                $plan->ds_cod =0;
            }
            $plan->od_charge =$request->od_charge;
            if ($request->od_cod=="on")
            {
                $plan->od_cod =1;
            }
            else
            {
                $plan->od_cod =0;
            }
            $plan->cpw =$request->cpw;
            $plan->save();
            toastr()->success('Plan created successfully');
            return redirect()->back();
        }
        toastr()->error('Plan name already exist.');
        return redirect()->back();
    }
    public function updatePlan(Request $request)
    {
        $plan = Plan::where('id',$request->id)->first();
        if ($plan->plan_name!=$request->plan_name)
        {
            $plan->plan_name =$request->plan_name;
        }

            $plan->idr_charge =$request->idr_charge;
            if ($request->idr_cod=="on")
            {
                $plan->idr_cod =1;
            }
            else
            {
                $plan->idr_cod =0;
            }
            $plan->idu_charge =$request->idu_charge;
            if ($request->idr_cod=="on")
            {
                $plan->idu_cod =1;
            }
            else
            {
                $plan->idu_cod =0;
            }
            $plan->ds_charge =$request->ds_charge;
            if ($request->ds_cod=="on")
            {
                $plan->ds_cod =1;
            }
            else
            {
                $plan->ds_cod =0;
            }
            $plan->od_charge =$request->od_charge;
            if ($request->od_cod=="on")
            {
                $plan->od_cod =1;
            }
            else
            {
                $plan->od_cod =0;
            }
            $plan->cpw =$request->cpw;
            $plan->save();
            toastr()->success("Plan updated successfully.");
            return redirect()->back();
        }
    public function coverageArea()
    {
        return view('admins.business-settings.coverage-area');
    }
    public function StoreCoverageArea(Request $request)
    {
        $id = $request->area;
        $area = Area::where('id',$id)->first();
        $city = City::where('id',$area->city_id)->first();
        $coverageArea1 = CoverageArea::where('area',$area->area_name)->where('city',$city->city_name)->first();
        $coverageArea = new CoverageArea;
        if (!empty($coverageArea1))
        {
            toastr()->error("Coverage area already Exists.");
            return redirect()->back();
        }
        $coverageArea->city = $city->city_name;
        $coverageArea->area = $area->area_name;
        $coverageArea->division = $request->division;
        $coverageArea->save();
        toastr()->success("Coverage area create successfully.");
        return redirect()->back();
    }
    public function status(Request $request){
        if($request->ajax())
        {
            $coverageArea = CoverageArea::where('id',$request->id)->first();
            $coverageArea->status = $request->status;
            $coverageArea->save();

        }
    }
}

resources/views/admins/business-settings/coverage-area.blade.php
@extends('admins.layouts.app')
@section('title')
    Merchant Request
@stop
@section('business','active')
@section('collapsed-business','')
@section('business-c','show')
@section('CAL','active')
@section('css')
    <style>
        .switch {
            position: relative;
            display: inline-block;
            width: 60px;
            height: 34px;
        }

        .switch input {
            opacity: 0;
            width: 0;
            height: 0;
        }

        .slider {
            position: absolute;
            cursor: pointer;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background-color: #ccc;
            -webkit-transition: .4s;
            transition: .4s;
        }

        .slider:before {
            position: absolute;
            content: "";
            height: 26px;
            width: 26px;
            left: 4px;
            bottom: 4px;
            background-color: white;
            -webkit-transition: .4s;
            transition: .4s;
        }

        input:checked + .slider {
            background-color: #2196F3;
        }

        input:focus + .slider {
            box-shadow: 0 0 1px #2196F3;
        }

        input:checked + .slider:before {
            -webkit-transform: translateX(26px);
            -ms-transform: translateX(26px);
            transform: translateX(26px);
        }

        /* Rounded sliders */
        .slider.round {
            border-radius: 34px;
        }

        .slider.round:before {
            border-radius: 50%;
        }
        .select2-container--default .select2-selection--single .select2-selection__rendered {
            color: #444;
            line-height: 28px;
            width: 180px;
        }
    </style>
@stop

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <div class="row p-0">
                        <div class="col text-left">
                            <h3>Coverage Area List</h3>
                        </div>
                        <div class="col text-right">
                            <button type="button" class="btn btn-success" data-toggle="modal" data-target="#plan-create-Modal"><i class='fas fa-plus'></i>Create Coverage Area</button>
                            <!--plan-create Modal -->
                            <div class="modal fade" id="plan-create-Modal" role="dialog">
                                <div class="modal-dialog modal-md">
                                    <!-- Modal content-->
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h4 class="modal-title">Coverage Area Details</h4>
                                            <button type="button" class="close btn btn-warning" data-dismiss="modal">&times;</button>
                                        </div>
                                        <form action="{{route('admin.business.store-coverage-area')}}" method="post">
                                            @csrf
                                            <div class="modal-body">
                                                <div class="container">
                                                    <div class="row">
                                                        <div class="col-xl-12">
                                                            <!-- Account details card-->
                                                            <div class="card mb-4">
                                                                <div class="card-body text-left">
                                                                    <div class="form-row">
                                                                        <!-- Form Group (first name)-->
                                                                        <div class="col-sm-6">
                                                                            <label>Area Name</label>
                                                                        </div>
                                                                        <!-- Form Group (last name)-->
                                                                        <div class="form-group col-sm-6">
                                                                            <select class="form-control pickup_area_select" id="area" name="area" >
                                                                                <option value="" selected disabled>Select area</option>
                                                                                @foreach (App\City::orderBy('city_name','asc')->get() as $city)
                                                                                    <optgroup label="{{$city->city_name}}">
                                                                                        @foreach(App\Area::where('city_id',$city->id)->orderBy('area_name','asc')->get() as $area)
                                                                                            <option value="{{$area->id}}">{{$area->area_name}}</option>
                                                                                        @endforeach
                                                                                    </optgroup>
                                                                                @endforeach
                                                                            </select>
                                                                        </div>
                                                                    </div>
                                                                    <div class="form-row">
                                                                        <!-- Form Group (first name)-->
                                                                        <div class="col-sm-6">
                                                                            <label>Sector Name</label>
                                                                        </div>
                                                                        <!-- Form Group (last name)-->
                                                                        <div class="form-group col-sm-6">
                                                                            <select class="form-control pickup_area_select" id="division" name="division" >
                                                                                <option value="Inside Dhaka" selected>Inside Dhaka</option>
                                                                                <option value="Outside Dhaka">Outside Dhaka</option>
                                                                                <option value="Dhaka Sub">Dhaka Sub</option>
                                                                            </select>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>

                                                    </div>

                                                </div>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="submit" class="btn btn-admin-primary" >Create</button>
                                                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-striped" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>Sector</th>
                                <th>City</th>
                                <th>Area</th>
                                <th>Status</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach(\App\CoverageArea::orderBy('id','desc')->get() as $coverageArea)
                                <tr>
                                    <td>{{$coverageArea->division}}</td>
                                    <td>{{$coverageArea->city}}</td>
                                    <td>{{$coverageArea->area}}</td>
                                    <td><label class="switch status"><input type="checkbox" class="status" id="{{$coverageArea->id}}" <?php if($coverageArea->status==1)echo "checked" ?>><span class="slider round"></span></label></td>

                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>


@stop
@section('script')
    @toastr_render
    <script>
        $("#area").select2({
            placeholder: "Select area",
            allowClear: false
        });
        $("#dataTable").dataTable();

        $(document).on('change','.status',function () {
            var id = $(this).attr("id");
            if($(this).prop("checked") == true){
                var status = 1;
            }
            else if($(this).prop("checked") == false){
                var status = 0;
            }

            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="_token"]').attr('content')
                }
            });
            $.ajax({
                url:"{{route('admin.business.status')}}",
                method: 'POST',
                data: {
                    id:id,
                    status:status
                },
                success:function () {
                    toastr.success('Coverage area status updated successfully');
                }
            });
        });
    </script>
@stop